# -*- coding: utf-8 -*-
"""Survey

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhCIxQroGX4ajLvy1H-mOeC_WJgHUdrF
"""

!pip install -q streamlit pyngrok sqlalchemy pandas

import os

os.makedirs("survey_app/pages", exist_ok=True)

print("Survey folders created.")

import os

os.makedirs("survey_app", exist_ok=True)
os.makedirs("survey_app/data", exist_ok=True)

print("Folders ready.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile survey_app/Survey.py
# 
# from __future__ import annotations
# 
# import re
# 
# import streamlit as st
# 
# from db import (
#     COMFORT_LEVELS,
#     TRAINING_AREAS,
#     USAGE_FREQUENCIES,
#     insert_response,
# )
# 
# 
# EMAIL_PATTERN = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
# 
# 
# st.set_page_config(
#     page_title="CURE | AI Training Survey",
#     page_icon="🧭",
#     layout="centered",
# )
# 
# st.markdown(
#     """
#     <style>
#     @import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@600;700&family=Inter:wght@400;500;600;700&display=swap');
# 
#     html, body, [class*="css"] {
#         font-family: 'Inter', sans-serif;
#         color: #dce3ec;
#         font-size: 16.5px;
#     }
#     h1, h2, h3 { font-family: 'Source Serif 4', serif; }
# 
#     /* Light glassy gray page background */
#     .stApp {
#         background: linear-gradient(135deg, #eceef1 0%, #e4e7eb 35%, #dcdfe4 65%, #e8eaed 100%);
#         background-attachment: fixed;
#     }
# 
#     .block-container {
#         max-width: 740px;
#         padding-top: 2.4rem;
#         padding-bottom: 3rem;
#     }
# 
#     /* Navy glass panels */
#     .hero {
#         text-align: center;
#         padding: 2.7rem 2rem 2.3rem 2rem;
#         border-radius: 14px;
#         background: linear-gradient(160deg, #101f38 0%, #0c1930 100%);
#         border: 1px solid rgba(148, 168, 199, 0.18);
#         box-shadow: 0 10px 30px rgba(8, 15, 28, 0.3);
#         margin-bottom: 1.6rem;
#     }
# 
#     .hero h1 {
#         color: #f4f7fb;
#         margin: 0.1rem 0 0.65rem 0;
#         font-size: 2.25rem;
#         font-weight: 700;
#         letter-spacing: -0.01em;
#     }
# 
#     .hero p {
#         color: #9fb2cc;
#         font-size: 1.04rem;
#         margin: 0;
#         line-height: 1.55;
#         font-family: 'Inter', sans-serif;
#     }
# 
#     [data-testid="stForm"] {
#         background: linear-gradient(160deg, #101f38 0%, #0c1930 100%);
#         border-radius: 14px;
#         padding: 2.2rem 2.2rem 0.6rem 2.2rem;
#         border: 1px solid rgba(148, 168, 199, 0.18);
#         box-shadow: 0 10px 30px rgba(8, 15, 28, 0.28);
#     }
# 
#     .section-tag {
#         display: block;
#         font-family: 'Inter', sans-serif;
#         color: #eef2f7;
#         font-weight: 600;
#         font-size: 1.1rem;
#         letter-spacing: 0.01em;
#         padding-bottom: 0.55rem;
#         margin-bottom: 1.15rem;
#         border-bottom: 1px solid rgba(148, 168, 199, 0.2);
#     }
# 
#     label, .stMarkdown, p, [data-testid="stWidgetLabel"] p {
#         color: #b9c6d9 !important;
#         font-size: 1.0rem !important;
#     }
#     .stCaption, [data-testid="stCaptionContainer"] {
#         color: #7387a3 !important;
#         font-size: 0.93rem !important;
#     }
# 
#     /* Inputs */
#     [data-testid="stTextInput"] input,
#     [data-testid="stTextArea"] textarea,
#     [data-testid="stTextInput"] > div > div,
#     [data-testid="stTextArea"] > div > div {
#         background-color: #17263f !important;
#         color: #f4f7fb !important;
#         -webkit-text-fill-color: #f4f7fb !important;
#         caret-color: #f4f7fb !important;
#         border: 1px solid rgba(148, 168, 199, 0.28) !important;
#         border-radius: 8px !important;
#         font-size: 1.0rem !important;
#     }
#     [data-testid="stTextInput"] input:focus,
#     [data-testid="stTextArea"] textarea:focus {
#         border-color: #6f8fb3 !important;
#         box-shadow: 0 0 0 2px rgba(111, 143, 179, 0.3) !important;
#         background-color: #1c2d4a !important;
#     }
# 
#     /* Placeholders — lighter & italic so they read as hints, not answers */
#     [data-testid="stTextInput"] input::placeholder,
#     [data-testid="stTextArea"] textarea::placeholder {
#         color: #56698a !important;
#         opacity: 0.85 !important;
#         font-style: italic;
#         font-weight: 400;
#     }
# 
#     [data-testid="stRadio"] label, [data-testid="stCheckbox"] label {
#         color: #c3cfe0 !important;
#         font-size: 1.0rem !important;
#     }
# 
#     [data-testid="stRadio"] input, [data-testid="stCheckbox"] input {
#         accent-color: #6f8fb3;
#     }
# 
#     /* Two-column row for name/email */
#     div[data-testid="column"] { padding: 0 0.5rem; }
#     div[data-testid="column"]:first-child { padding-left: 0; }
#     div[data-testid="column"]:last-child { padding-right: 0; }
# 
#     hr { border-color: rgba(148, 168, 199, 0.18); margin: 1.7rem 0; }
# 
#     /* Submit button — always the bright, highlighted state */
#     div.stButton > button, [data-testid="stFormSubmitButton"] button {
#         background: linear-gradient(135deg, #2c5aa0, #3d74c4);
#         color: #ffffff;
#         border: 1px solid #4a86d6;
#         border-radius: 8px;
#         padding: 0.85rem 1rem;
#         font-weight: 600;
#         font-family: 'Inter', sans-serif;
#         font-size: 1.04rem;
#         letter-spacing: 0.01em;
#         box-shadow: 0 6px 20px rgba(61, 116, 196, 0.45);
#         transition: background 0.2s ease, box-shadow 0.2s ease, transform 0.1s ease;
#     }
#     div.stButton > button:hover, [data-testid="stFormSubmitButton"] button:hover {
#         background: linear-gradient(135deg, #33629c, #467fd0);
#         transform: translateY(-1px);
#         box-shadow: 0 8px 24px rgba(61, 116, 196, 0.55);
#     }
# 
#     .cure-footer {
#         text-align: center;
#         margin-top: 1.6rem;
#         font-family: 'Inter', sans-serif;
#         font-size: 0.82rem;
#         color: #6b7280;
#         letter-spacing: 0.02em;
#     }
#     </style>
#     """,
#     unsafe_allow_html=True,
# )
# 
# 
# if st.session_state.get("submitted"):
#     st.markdown(
#         """
#         <div class="hero">
#             <h1>Thank You</h1>
#             <p>Your response has been recorded and the team has been notified.</p>
#         </div>
#         """,
#         unsafe_allow_html=True,
#     )
#     st.balloons()
#     st.stop()
# 
# 
# st.markdown(
#     """
#     <div class="hero">
#         <h1>AI Training Survey</h1>
#         <p>Help us build an AI training program that actually fits how you work.</p>
#     </div>
#     """,
#     unsafe_allow_html=True,
# )
# 
# 
# with st.form("survey_form"):
# 
#     st.markdown('<div class="section-tag">Your Details</div>', unsafe_allow_html=True)
# 
#     col_name, col_email = st.columns(2)
# 
#     with col_name:
#         name = st.text_input("Full Name *", placeholder="Jane Doe")
# 
#     with col_email:
#         email = st.text_input("Email Address *", placeholder="jane.doe@cure.com")
# 
#     st.divider()
# 
#     st.markdown('<div class="section-tag">Current AI Usage</div>', unsafe_allow_html=True)
#     usage_frequency = st.radio(
#         "How frequently do you currently use AI tools for work?",
#         USAGE_FREQUENCIES,
#         index=None,
#     )
#     usage_explanation = st.text_area(
#         "Briefly explain how you currently use AI at work.",
#         placeholder="e.g. drafting emails, analyzing documents, coding, research, summarizing information",
#     )
# 
#     st.divider()
# 
#     st.markdown('<div class="section-tag">Comfort Level</div>', unsafe_allow_html=True)
#     comfort_display_labels = [label for _, label in COMFORT_LEVELS]
#     comfort_choice = st.radio(
#         "How comfortable are you using AI tools effectively?",
#         comfort_display_labels,
#         index=None,
#     )
# 
#     st.divider()
# 
#     st.markdown('<div class="section-tag">Training Interests</div>', unsafe_allow_html=True)
#     st.caption("Select all that apply.")
#     selected_areas = []
#     for area in TRAINING_AREAS:
#         if st.checkbox(area, key=f"area_{area}"):
#             selected_areas.append(area)
# 
#     other_training_area = ""
#     if "Other" in selected_areas:
#         other_training_area = st.text_input("Please specify the other training area")
# 
#     st.divider()
# 
#     st.markdown('<div class="section-tag">Repetitive Task</div>', unsafe_allow_html=True)
#     repetitive_task = st.text_area(
#         "What repetitive or manual task takes up the most time in your current role?",
#         placeholder="e.g. copying data between spreadsheets, formatting weekly reports, manual QA checks",
#         label_visibility="collapsed",
#         height=110,
#     )
# 
#     st.divider()
# 
#     st.markdown('<div class="section-tag">Your AI Wishlist</div>', unsafe_allow_html=True)
#     desired_improvement = st.text_area(
#         "If AI could make one part of your job significantly easier, what would you want it to do?",
#         placeholder="e.g. automate a process, analyze documents, create reports, generate test cases",
#         label_visibility="collapsed",
#         height=110,
#     )
# 
#     st.write("")
#     submitted = st.form_submit_button("Submit Survey", use_container_width=True)
# 
# 
# if submitted:
#     errors = []
# 
#     if not name.strip():
#         errors.append("Please enter your full name.")
# 
#     if not email.strip():
#         errors.append("Please enter your email address.")
#     elif not EMAIL_PATTERN.match(email.strip()):
#         errors.append("Please enter a valid email address.")
# 
#     if errors:
#         for message in errors:
#             st.error(message)
#     else:
#         comfort_value = (
#             COMFORT_LEVELS[comfort_display_labels.index(comfort_choice)][0]
#             if comfort_choice
#             else ""
#         )
# 
#         insert_response(
#             name=name.strip(),
#             email=email.strip(),
#             usage_frequency=usage_frequency or "",
#             usage_explanation=usage_explanation,
#             comfort_level=comfort_value,
#             training_areas=selected_areas,
#             other_training_area=other_training_area,
#             repetitive_task=repetitive_task,
#             desired_improvement=desired_improvement,
#         )
# 
#         st.session_state["submitted"] = True
#         st.rerun()
# 
# st.markdown('<div class="cure-footer">CURE · AI Enablement Initiative</div>', unsafe_allow_html=True)

"""EMail Notfication config"""

from google.colab import drive

drive.mount('/content/drive')

import os

RESPONSE_FOLDER = "/content/drive/MyDrive/AI_Training_Survey"

os.makedirs(RESPONSE_FOLDER, exist_ok=True)

print("Response folder ready:")
print(RESPONSE_FOLDER)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile survey_app/db.py
# 
# from __future__ import annotations
# 
# import csv
# import os
# from datetime import datetime
# 
# 
# # ---------------------------------------
# # Survey choices
# # ---------------------------------------
# 
# USAGE_FREQUENCIES = [
#     "Daily",
#     "A few times per week",
#     "Occasionally",
#     "Rarely",
#     "Never",
# ]
# 
# 
# COMFORT_LEVELS = [
#     (
#         "Beginner",
#         "Beginner — limited or no experience"
#     ),
#     (
#         "Intermediate",
#         "Intermediate — use AI for some work tasks"
#     ),
#     (
#         "Advanced",
#         "Advanced — regularly use AI for more complex tasks"
#     ),
# ]
# 
# 
# TRAINING_AREAS = [
#     "Writing and improving emails, reports, and business documents",
#     "Document analysis and summarization",
#     "Analyzing information across multiple documents/files",
#     "Data and spreadsheet analysis",
#     "Jira — requirements, test cases and defect management",
#     "Creating test cases using AI",
#     "Automation testing",
#     "Process/workflow automation",
#     "Creating presentations and visual content",
#     "Creating UI mockups/prototypes",
#     "Coding, debugging and technical assistance",
#     "Searching/analyzing information from company folders and emails",
#     "Metrics, monitoring and alert logic",
#     "AI privacy, security and responsible use",
#     "Other",
# ]
# 
# 
# # ---------------------------------------
# # Response file in Google Drive
# # ---------------------------------------
# 
# RESPONSE_FILE = (
#     "/content/drive/MyDrive/"
#     "AI_Training_Survey/"
#     "AI_Training_Survey_Responses.csv"
# )
# 
# 
# # ---------------------------------------
# # Save response
# # ---------------------------------------
# 
# def insert_response(
#     *,
#     name,
#     email,
#     usage_frequency,
#     usage_explanation,
#     comfort_level,
#     training_areas,
#     other_training_area,
#     repetitive_task,
#     desired_improvement,
# ):
# 
#     file_exists = os.path.exists(RESPONSE_FILE)
# 
#     with open(
#         RESPONSE_FILE,
#         "a",
#         newline="",
#         encoding="utf-8-sig"
#     ) as file:
# 
#         writer = csv.writer(file)
# 
#         if not file_exists:
# 
#             writer.writerow([
#                 "Timestamp",
#                 "Full Name",
#                 "Email",
#                 "AI Usage Frequency",
#                 "AI Usage Explanation",
#                 "Comfort Level",
#                 "Training Areas",
#                 "Other Training Area",
#                 "Repetitive Task",
#                 "AI Wishlist",
#             ])
# 
#         writer.writerow([
#             datetime.now().strftime(
#                 "%Y-%m-%d %H:%M:%S"
#             ),
#             name,
#             email,
#             usage_frequency,
#             usage_explanation,
#             comfort_level,
#             ", ".join(training_areas),
#             other_training_area,
#             repetitive_task,
#             desired_improvement,
#         ])

!pip install -q streamlit pyngrok

from pyngrok import ngrok

ngrok.set_auth_token(
    "3ImJX6ciRqDCoDpy811QNkg7lMb_5yLLHJzUbfLoxicxnaALJ"
)

print("ngrok configured successfully.")

import subprocess
import time

!pkill -f "streamlit run" || true

process = subprocess.Popen(
    [
        "streamlit",
        "run",
        "survey_app/Survey.py",
        "--server.port", "8501",
        "--server.headless", "true",
        "--server.enableCORS", "false",
    ]
)

time.sleep(8)

print("Survey started on port 8501")

from pyngrok import ngrok

try:
    ngrok.kill()
except:
    pass

public_url = ngrok.connect(8501)

print("AI Training Survey URL:")
print(public_url)

